-- Domínio CPF
CREATE DOMAIN CPF_T AS CHAR(11)
CHECK (VALUE SIMILAR TO '\d{11}');
-- Dominio telefone
CREATE DOMAIN TELEFONE_T AS VARCHAR(9)
CHECK (
    VALUE SIMILAR TO '9\d{8}' OR
    VALUE SIMILAR TO '\d{8}'
);
-- Dominio de unsigned int
CREATE DOMAIN UINT_T AS INTEGER
CHECK (VALUE >= 0);

-- Tabela seção
CREATE TABLE SECAO(
    COD_SECAO SERIAL,
    NOME_SECAO VARCHAR(20) UNIQUE,
    QUANTIDADE_PROD UINT_T DEFAULT 0,

    PRIMARY KEY (COD_SECAO)
);
-- Tabela cliente
CREATE TABLE CLIENTE(
    CPF_CLIENTE CPF_T,
    NOME_CLIENTE VARCHAR(15),
    TELEFONE_CLIENTE TELEFONE_T,

    PRIMARY KEY(CPF_CLIENTE),
);
-- Tabela funcionário
CREATE TABLE FUNCIONARIO(
    CPF_FUNC CPF_T,
    SALARIO MONEY NOT NULL,
    NOME VARCHAR(15) NOT NULL,
    SOBRENOME VARCHAR(15),
    TELEFONE_FUNC TELEFONE_T,
    TIPO_FUNC INTEGER NOT NULL,
    NUMERO_CAIXA UINT_T,
    COD_SECAO_AUXILIADA INTEGER,

    PRIMARY KEY(CPF_FUNC),
    FOREIGN KEY (COD_SECAO_AUXILIADA) REFERENCES SECAO(COD_SECAO) ON DELETE NO ACTION,
    CHECK (SALARIO > CAST(1000.00 AS MONEY) AND TIPO_FUNC >= 1 AND TIPO_FUNC <= 3)
);
-- Tabela telefones de emergencia
CREATE TABLE TELEFONES_EMERGENCIA(
    CPF_FUNC CPF_T,
    TELEFONE TELEFONE_T,
 
    PRIMARY KEY(CPF_FUNC , TELEFONE),
    FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIO(CPF_FUNC) ON DELETE CASCADE,
);
-- Tabela organiza
CREATE TABLE ORGANIZA(
    CPF_FUNC CPF_T,
    COD_SECAO INTEGER,
    DATA_ DATE,
 
    PRIMARY KEY(CPF_FUNC , COD_SECAO, DATA_),
    FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIO(CPF_FUNC) ON DELETE CASCADE,
    FOREIGN KEY(COD_SECAO) REFERENCES SECAO(COD_SECAO) ON DELETE CASCADE,
);
-- Tabela produto
CREATE TABLE PRODUTO(
    COD_PROD SERIAL,
    NOME_PROD VARCHAR(20) NOT NULL,
    PRECO MONEY NOT NULL,
    DESCRICAO VARCHAR(50),
    QUANTIDADE UINT_T,
    COD_SECAO INTEGER NOT NULL,
    MARCA VARCHAR(20),

    PRIMARY KEY(COD_PROD),
    FOREIGN KEY(COD_SECAO) REFERENCES SECAO(COD_SECAO) ON DELETE NO ACTION,
    CHECK (PRECO > CAST(0 AS MONEY)),
    UNIQUE(NOME_PROD, MARCA)
)
-- Tabela vende
CREATE TABLE VENDE(
    ID_VENDA INTEGER,
    COD_PROD INTEGER,
    CPF_CLIENTE CPF_T,
    CPF_FUNC CPF_T,
    QUANTIDADE_VENDIDA UINT_T,

    PRIMARY KEY(ID_VENDA, COD_PROD, CPF_CLIENTE, CPF_FUNC),
    FOREIGN KEY(COD_PROD) REFERENCES PRODUTO(COD_PROD) ON DELETE NO ACTION,
    FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF_CLIENTE) ON DELETE NO ACTION,
    FOREIGN KEY(CPF_FUNC) REFERENCES FUNCIONARIO(CPF_FUNC) ON DELETE NO ACTION,
);