INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Massas', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Biscoitos', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Higiene', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Carnes', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Legumes', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Congelados', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Frutas', 0);
INSERT INTO SECAO(NOME_SECAO, QUANTIDADE_PROD) VALUES('Bebidas', 0);